spring:
  task:
    scheduling:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    listener:
      simple:
        auto-startup: false

app:
  jwt:
    secret: 01234567890123456789012345678901
  outbox:
    publisher-delay-ms: 600000
  reconciliation:
    delay-ms: 600000
