CREATE TABLE accounts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  account_number VARCHAR(20) UNIQUE NOT NULL,
  ifsc VARCHAR(20) NOT NULL,
  bank_name VARCHAR(100) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_acc_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE balances (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT UNIQUE NOT NULL,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  version BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bal_acc FOREIGN KEY (account_id) REFERENCES accounts(id)
);
