CREATE TABLE vpas (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  handle VARCHAR(100) UNIQUE NOT NULL,
  user_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vpa_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_vpa_acc FOREIGN KEY (account_id) REFERENCES accounts(id)
);
