CREATE TABLE collect_requests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  request_ref VARCHAR(64) UNIQUE NOT NULL,
  from_vpa VARCHAR(100) NOT NULL,
  to_vpa VARCHAR(100) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  note VARCHAR(255),
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  txn_id BIGINT,
  idempotency_key VARCHAR(128),
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cr_txn FOREIGN KEY (txn_id) REFERENCES transactions(id)
);
